CREATE TABLE
    SGCUNIDADES
    (
        UNDCOD VARCHAR,
        UNDNAME VARCHAR,
        UNDADDRESS VARCHAR,
        UNDDISTRICT VARCHAR,
        UNDCITY VARCHAR,
        UNDESTATE VARCHAR,
        UNDRESPONSIBLE VARCHAR
    );